-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVnH/KtfrytiPDDyV
4WQOyLMW4oVDU2sb3Q8g5XhAwcSgCgYIKoZIzj0DAQehRANCAASm8pAgpzSqZxKP
uU3gKPReVsEJnitjYAK0N0QLk3/aMIMP2Sd+0aCNCaSPgLge+tEhVmrTXCB1+VUy
oSame9fy
-----END PRIVATE KEY-----